substitutions:
  _IMAGE: europe-west8-docker.pkg.dev/istat-ndc-schema-ass-cms-dev/schema-assistant/web:dev

steps:
  - id: build-web
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
